### PR TITLE
Init create functions for dump and print node

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I think this is ready for start, the package need to be registered to packagist, per composer name, to be:

`rector/rector-debugging`

**Comment by TomasVotruba** [comment]
I'm going to add it to packagist right now :+1:

**Comment by TomasVotruba** [comment]
There is it :slightly_smiling_face: 
https://packagist.org/packages/rector/rector-debugging

**Comment by samsonasik** [comment]
Thank you 👍 , I created PRs to repos, including rector-src to require-dev rector/rector-debugging

**Pull request merged**
